services:
  db:
    image: postgres:16
    container_name: tfm_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: tfm
      POSTGRES_PASSWORD: tfm
      POSTGRES_DB: tfm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tfm -d tfm"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
